### ISSUE TITLE
Project tests fail if I18n plugin is not included

### ISSUE THREAD

**Issue by ericvera** [infinitered/ignite-ir-next#13]
`boilerplate/Tests/Setup.js` has a reference to I18n.

**Comment by GantMan** [comment]
awesome!  Will fix.  Would you like to give it a go first?

PRs welcome!

**Comment by ericvera** [comment]
Working on the move to Jest at the moment. I'll let you know if I get to it before somebody else. This is mostly an issue when testing plugins with --min option so not urgent. If other people see this I can take a look sooner.

**Comment by ruddell** [comment]
This is the same issue as https://github.com/infinitered/ignite/issues/911 

I submitted a PR on the 2016 boilerplate https://github.com/infinitered/ignite-ir-boilerplate-2016/pull/20

**Comment by jamonholmgren** [comment]
I'm working on a port of that over to here. THanks @ruddell for fixing this!
