### ISSUE TITLE
White flash on transition

### ISSUE THREAD

**Issue by jhblacklock** [infinitered/ignite-ir-next#14]
I got this boilerplate setup with CRNA and it's working great! Thanks.

I do see a white flash, seems to be loading styles like bg color later in the render, so the initial page load starts with a white bg.  Tested a greenfield bootstrap install in the ios emulator and did not see that issue.  Wondering if it's a CRNA thing or maybe expo?

Thanks!

**Comment by jhblacklock** [comment]
I was able to mitigate this issue modifying StackNavigator

``` javascript
export default StackNavigator({
  PresentationScreen: {screen: PresentationScreen},
  APITestingScreen: {screen: APITestingScreen},
  ComponentExamplesScreen: {screen: ComponentExamplesScreen},
  PluginExamplesScreen: {screen: PluginExamplesScreen},
  ThemeScreen: {screen: ThemeScreen},
  FaqScreen: {screen: FaqScreen}
}, {
  cardStyle: {
    opacity: 1,
    backgroundColor: '#3e243f'
  },
  initialRouteName: 'PresentationScreen',
  headerMode: 'none',
  // Keeping this here for future when we can make
  navigationOptions: {
    header: {
      left: (
        <TouchableOpacity onPress={() => window.alert('pop')} ><Image source={Images.closeButton} style={{marginHorizontal: 10}} /></TouchableOpacity>
      ),
      style: {
        backgroundColor: '#3e243f'
      }
    }
  }
})
```

Happy to create a PR if needed.

**Comment by GantMan** [comment]
That's interesting.   We might need that PR, let me see if I can get a local test with the same result.

**Comment by jhblacklock** [comment]
Got it queued up if needed.

**Comment by GantMan** [comment]
@ryanlntn are you seeing this same problem with your current app?

**Comment by GantMan** [comment]
how are you liking building expo with ignite btw  @jhblacklock ?  That's on our todo list.

**Comment by jhblacklock** [comment]
Great IMO.  Although I haven't gotten far.

I just attached ignite to a create-react-native-app.  Had to reconfigure the entry point, removed `index.ios.js` and `index.android.js`, added `index.js` to `/App` and copied `App/Containers/App.js` to `/App/index.js` then removed `App/Containers/App.js`. I also manually copied over the ignite folder and contents, and merged package.json.

I've only tested on ios but so far so good. Real smooth.

FYI, I guess this issue is really a https://github.com/infinitered/ignite DevScreens thing 😄 I modifed that repo in a PR.

**Comment by ryanlntn** [comment]
@GantMan I've been mainly using TabNavigator so I didn't notice until today. The StackNavigator definitely exhibits this issue.

**Comment by jamonholmgren** [comment]
@ryanlntn Is this still an issue?

**Comment by ryanlntn** [comment]
@jamonholmgren It doesn't show up for me with a newly ignited app. Closing this for now.
