### ISSUE TITLE
Error when generating listview

### ISSUE THREAD

**Issue by jvanderwee** [infinitered/ignite-ir-next#16]
Running ignite g listview TestScreen successfully generates but outputs:
```
vvv -----[ DEBUG ]----- vvv
TypeError: print.log is not a function
    at Object.module.exports [as run] (/Users/joe/Documents/TestIgniteApp/node_modules/ignite-ir-next/commands/listview.js:95:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
^^^ -----[ DEBUG ]----- ^^^
```

ignite doctor:
```
System
  platform           darwin
  arch               x64
  cpu                4 cores                                 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
  directory          /Users/joe/Documents/TestIgniteApp

JavaScript
  node               7.8.0        /usr/local/bin/node
  npm                4.2.0        /usr/local/bin/npm
  yarn               0.22.0       /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1
  app rn version     0.42.0

Ignite
  ignite             2.0.0-beta.8   /usr/local/bin/ignite

Android
  java               1.8.0_45     /usr/bin/java
  android home       -            /Users/joe/Library/Android/sdk

iOS
  xcode              8.3
```

**Comment by GantMan** [comment]
Hrmmmm, taking a look at that line on Master looks like there's been some changes.
https://github.com/infinitered/ignite-ir-next/blob/master/commands/listview.js#L95

Can you firstly do `ignite add ir-next` to make sure you've got latest on node.

If that doesn't work: pull that code with a clone to `git@github.com:infinitered/ignite-ir-next.git` and then install it with `ignite add /path/to/master/` and see if that fixes your issue?

I'm interested where the disconnect is.

**Comment by skellock** [comment]
https://github.com/infinitered/ignite-ir-next/blob/master/commands/listview.js#L100

`print.log` isn't a thing.   `print.info` is though.

**Comment by GantMan** [comment]
hahahaha, PR needed
