### ISSUE TITLE
Add Jest snapshot tests

### ISSUE THREAD

**Issue by derekgreenberg** [infinitered/ignite-ir-next#36]
- replace "Tests/Setup.js" with Jest mocks and ensure existing component tests still run, otherwise fix issues.
- Add "updateSnapshot": "jest --updateSnapshot" as a script in package.json
- If a snapshot test of an ignite-ir-next component covers 100% of the code, replace the unit test with a snapshot test
- Otherwise, supplement the snapshot test with enzyme/shallow tests to exercise code that is not covered by the snapshot test. A simple example is a component with an onPress handler that invokes the handler that was passed in as a prop. The snapshot test does not cover this.

**Comment by derekgreenberg** [comment]
@jamonholmgren This can be closed. See `https://github.com/infinitered/ignite-ir-next/pull/48`

**Comment by jamonholmgren** [comment]
Thank you @derekgreenberg !
