### ISSUE TITLE
Removing getUser from Api.js results in error

### ISSUE THREAD

**Issue by hnprashanth** [infinitered/ignite-ir-next#41]
Hi,

I'm new to react-native & ignite, was following the YouTube guide on how to add API to the application.
There seems to be some kind of dependency on getUser since removing this API results in error. I tried removing other two APIs getRate and getRoot, but they were fine. 
I'm getting "uncaught at check call argument fn is undefined" 
Since I'm new to this, I'm not able to debug what's going on here, but should have worked fine as per the YouTube guide.
<img width="377" alt="screen shot 2017-05-17 at 10 34 41 am" src="https://cloud.githubusercontent.com/assets/379689/26139206/81e79a0a-3aec-11e7-94f2-ab6170df0905.png">

**Comment by GantMan** [comment]
I wonder if there's something inside the saga?  Can you do a find-all?  I bet the saga is looking for that API call.

**Comment by hnprashanth** [comment]
Yes, there is reference from GithubSagas.js which has a reference from Sagas/index.js, I'm wondering why every application would require Github getUser!

**Comment by hnprashanth** [comment]
I'm following YouTube guide to the T - https://www.youtube.com/watch?v=GUZJr6Dyok0&t=180s
When I do what is show at 3 minute mark, I get this error.

**Comment by hnprashanth** [comment]
Removed all references and this seems to be working (no error, but API not working as expected, closing this as it's not related).

**Comment by kiang** [comment]
Met the same problem as following the same video guide. Maybe is should be noted somewhere.
