### ISSUE TITLE
Unhandled JS Exception: console.tron.overlay is not a function

### ISSUE THREAD

**Issue by heyjared** [infinitered/ignite-ir-next#49]
When running a release build on my device, I get the following exception:
```
Unhandled JS Exception: console.tron.overlay is not a function. (In 'console.tron.overlay(f)', 'console.tron.overlay' is undefined
```
This causes the app to terminate, due to Reactotron not being available in non-DEV builds. Other tron functions are not affected because they are mocked in ReactotronConfig.

I solved this temporarily by removing the overlay in App.js and using the unmodified App instead of AppWithBenefits.

**Comment by skellock** [comment]
Thanks.  Ya, this is an issue.  Thanks for bringing this up.

There's a better solution to this [incoming shortly](https://github.com/infinitered/reactotron/issues/433).  In the mean time, it's a good idea to either do what you did, or protect it behind a conditional.

**Comment by engmsaleh** [comment]
I have struggled for two days with this issue, the problem that when I submit the build to TestFlight,  when I install the App, the App open the splash screen and crashes immediately, without any obvious problem.

It ends up that I changed that line in `App.js` file from 
`const AppWithBenefits = console.tron.overlay(App)`
into
`export default App`

**Comment by jamonholmgren** [comment]
@engmsaleh Yes, this is a rough one, we're working on it!

**Comment by GantMan** [comment]
Yup this was a super sneaky bug.  I recently had the same issue only yesterday!

As you can see there's an update to Reactotron which solves this 👍 

Another easy way is to add the overlay stub in production here:  https://github.com/infinitered/ignite-ir-next/blob/master/boilerplate/App/Config/ReactotronConfig.js#L54-L61
