### ISSUE TITLE
Integration tests creating githooks error

### ISSUE THREAD

**Issue by robinheinze** [infinitered/ignite-ir-next#51]
After running integration tests, the following error spits out when running git commands:

`line 18: cd: IntegrationTest/IntegrationTest: No such file or directory`

There's an error for each hook, so on commit, it spits out: 

```
.git/hooks/pre-commit: line 18: cd: IntegrationTest/IntegrationTest: No such file or directory
.git/hooks/prepare-commit-msg: line 18: cd: IntegrationTest/IntegrationTest: No such file or directory
.git/hooks/commit-msg: line 18: cd: IntegrationTest/IntegrationTest: No such file or directory
.git/hooks/post-commit: line 18: cd: IntegrationTest/IntegrationTest: No such file or directory
.git/hooks/post-rewrite: line 18: cd: IntegrationTest/IntegrationTest: No such file or directory
```

It doesn't seem to block the git action, (i.e. Still able to commit and push successfully).

**Comment by jamonholmgren** [comment]
@robinheinze I've noticed this for a while and am constantly aggravated by it. I haven't had time to look into it. I just run `rm -rf ./.git/hooks` each time ;)

**Comment by jamonholmgren** [comment]
I don't think we should integrate husky or git hooks into our boilerplate at all, btw.

**Comment by jamonholmgren** [comment]
#53 fixes this issue by removing husky (temporarily, but I think it should be permanently, and make husky an optional plugin)

**Comment by skellock** [comment]
It's an issue because we're running the integration tests within an existing repo.  Repo in a repo isn't a good thing.

I'm happy to see `husky` go for the boilerplate.
